FROM node:20
WORKDIR /app

# Create minimal package.json
RUN npm init -y

# Install PostCSS CLI and plugins
RUN npm install postcss postcss-cli tailwindcss autoprefixer @tailwindcss/postcss

# Copy shared folder into image
COPY shared/f-tailcss /app/f-tailcss/
COPY shared/postcss.config.js /app/postcss.config.js
COPY shared/tailwind.config.js /app/tailwind.config.js
