version: "3.8"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  nodeapp:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
